# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blocksite < Formula
  desc ""
  homepage "https://github.com/omerxx/go-blocksite"
  version "0.1.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/omerxx/go-blocksite/releases/download/v0.1.1/go-blocksite_Darwin_arm64.tar.gz"
      sha256 "92d97ece0346a520241cab9e94b8afebcd11ba52dec274f76053e2be1a7ccbb9"

      def install
        bin.install "go-blocksite"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omerxx/go-blocksite/releases/download/v0.1.1/go-blocksite_Darwin_x86_64.tar.gz"
      sha256 "138c72b35d03d77f5008bfdfdd5470a19b366621ba1b6e91bd23af3120caf8ae"

      def install
        bin.install "go-blocksite"
      end
    end
  end
end
