# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssox < Formula
  desc ""
  homepage "https://github.com/omerxx/ssox"
  version "0.1.6"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/omerxx/ssox/releases/download/v0.1.6/ssox_Darwin_arm64.tar.gz"
      sha256 "ab70f3a497cb47f9152cb53d921f07c4d6573d1cd11e018fc1145a80f2703187"

      def install
        bin.install "ssox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omerxx/ssox/releases/download/v0.1.6/ssox_Darwin_x86_64.tar.gz"
      sha256 "e1284a20ea03c589609a74cb60def612708c1f92cb1c2015088e59278bb84ba7"

      def install
        bin.install "ssox"
      end
    end
  end
end
